---
title: "lab3"
author: "Vitalii Borysov"
date: "15/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.

```{r}
add2 <- function(x, y){
  return(x + y)
}

add2(13, 54)
add2(5533, 4124)
```

2.

```{r}
above <- function(x, n=10){
  result <- x[x>n]
  return(result)
}

above(c(1, 15, 6, 14, 55, 2, 6, 87))
above(c(1, 15, 6, 14, 55, 2, 6, 87), 50)
```

3.

```{r}

my_ifelse <- function(x, exp, n){
  result <- switch(exp, 
                   "<" = x[x<n],
                   ">" = x[x>n],
                   "<=" = x[x<=n],
                   ">=" = x[x>=n],
                   "==" = x[x==n],
                   "!=" = x[x!=n],
                   x)
  return(result)
}

my_ifelse_test_vector <- c(-14, 23, -5, 3, 0, 66, -34, 54, 133, 7656, 5, -545, 34)
my_ifelse(my_ifelse_test_vector, ">", 0)
my_ifelse(my_ifelse_test_vector, ">=", 0)
my_ifelse(my_ifelse_test_vector, "<", 0)
my_ifelse(my_ifelse_test_vector, "<=", 0)
my_ifelse(my_ifelse_test_vector, "==", 0)
my_ifelse(my_ifelse_test_vector, "!=", 0)
my_ifelse(my_ifelse_test_vector, "not_found", 0)
```

4.

```{r}
columnmean <- function(x, removeNA=TRUE){
  list_res <- list()
  for(col in names(x)){
    mean_value <- sum(x[[col]][!is.na(x[[col]])]) / length(x[[col]])
    if(removeNA){
      mean_value <- mean(x[[col]][!is.na(x[[col]])])
    }
    
    list_res <- append(list_res, cat(col, mean_value, ";"))
  }
  
  return(list_res)
}

test_dataframe <- data.frame("a"=1:3, "b"=c(10, 14, NA), "c"=c(30, NA, NA))

columnmean(test_dataframe)
columnmean(test_dataframe, FALSE)
```



