---
title: "lab6"
author: "Vitalii Borysov"
date: "15/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Task 1
```{r}
ncol <- 5
nrow <- 10

#Task1
mat <- matrix(rnorm(50), ncol = ncol, nrow = nrow)

mat
```

Task 2
```{r}
#Task2
for(col in 1:ncol){
  print(max(mat[,col]))
}
```

Task 3
```{r}
#Task3
for(col in 1:ncol){
  print(mean(mat[,col]))
}
```

Task 4
```{r}
#Task4
for(col in 1:ncol){
  print(min(mat[col,]))
}
```

Task 5
```{r}
#Task5
for(col in 1:ncol){
  print(col)
  print(sort(mat[,col]))
}
```

Task 6
```{r}
#Task6
find_zero_greater_count <- function(mat, ncol){
  for(col in 1:ncol){
    print(length(mat[,col][mat[,col]<0]))
  }
}

find_zero_greater_count(mat, ncol)
```

Task 7
```{r}
#Task7
bool_arr <- vector()
for(col in 1:ncol){
  if(length(mat[,col][mat[,col]>2])){
    bool_arr<-c(bool_arr, TRUE)
  }
  else{
    bool_arr<-c(bool_arr, FALSE)
  }
}

bool_arr
```

Task 8
```{r}
#Task8
list1 <- list(observationA = c(1:5, 7:3),
              observationB =matrix(1:6, nrow=2))
list1

lapply(list1, sum)
```

Task 9
```{r}
#Task9
lapply(list1, min)
lapply(list1, max)

sapply(list1, min)
sapply(list1, max)
```

Task 10
```{r}
#Task10
data <- InsectSprays

result <- aggregate(list(MeanCount=data$count), list(Spray=data$spray), mean)

head(data, 10)
result
```







